### ISSUE TITLE
not responsive for size higher then  450px

### ISSUE THREAD

**Issue by bayan-404** [GSG-K3/News-Translation#26]
the earth goes to the right

**Comment by karmelyoei** [comment]
This is app- first so, at default 360*640 for the mobile, its responsive but for other dimensions we didn't consider as unrequired. our only concerns were only as an app, not as a website, therefore we focused only on the code rather than the design itself, please close this issue if you find this replay an answer for your issue

**Comment by bayan-404** [comment]
we can open apps in iPad and it's 708*1024

**Comment by karmelyoei** [comment]
Ipad its an Ipad, not a smartphone any way I will consider your opinion
